

# Mostra as queries no console
spring.jpa.show-sql=true

# Atualiza o schema automaticamente
spring.jpa.hibernate.ddl-auto=update

# Dialeto específico do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta do servidor
server.port=8080

# Chave do JWT

jwt.secret=ce6a187d-ec00-4716-a3d7-879b8df42426
jwt.expiracao=28800000